version: '3'
services:
  # laravel-stripe
  larvel-stripe:
    build:
      context: ./../laravel-stripe
      dockerfile: ../docker/dockerfiles/larvel-stripe-Dockerfile
    env_file: .env
    environment:
      API_GW_HOST: api-gw
    volumes:
      - ./../laravel-stripe:/application
    ports:
      - "8000:8000"
